# Generated by Django 2.2 on 2021-09-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('main_pic', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('beds', models.IntegerField()),
                ('bath', models.IntegerField()),
                ('square_feet', models.IntegerField()),
            ],
        ),
    ]
